# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

apnorm <- function(u) {
    .Call(`_skewfit_apnorm`, u)
}

cGetEw <- function(x, eta, sig2) {
    .Call(`_skewfit_cGetEw`, x, eta, sig2)
}

cSlm0 <- function(y, x) {
    .Call(`_skewfit_cSlm0`, y, x)
}

cSlm1 <- function(y, x) {
    .Call(`_skewfit_cSlm1`, y, x)
}

cSlm <- function(y, x) {
    .Call(`_skewfit_cSlm`, y, x)
}

fit_para_skew <- function(init_pa, y, x, z, max_steps, tol) {
    .Call(`_skewfit_fit_para_skew`, init_pa, y, x, z, max_steps, tol)
}

fit_iso_norm <- function(init_pa, init_ai, y, x, z, unimodal, max_steps, tol) {
    .Call(`_skewfit_fit_iso_norm`, init_pa, init_ai, y, x, z, unimodal, max_steps, tol)
}

fit_iso_skew <- function(pa, ai, y, x, z, unimodal, usez, max_steps, tol) {
    .Call(`_skewfit_fit_iso_skew`, pa, ai, y, x, z, unimodal, usez, max_steps, tol)
}

cPava <- function(y, w) {
    .Call(`_skewfit_cPava`, y, w)
}

FPava <- function(y, w) {
    .Call(`_skewfit_FPava`, y, w)
}

FUfit <- function(y, w) {
    .Call(`_skewfit_FUfit`, y, w)
}

cIso <- function(y, unimodal) {
    .Call(`_skewfit_cIso`, y, unimodal)
}

