# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cGetEw <- function(x, eta, sig2) {
    .Call(`_skewfit_cGetEw`, x, eta, sig2)
}

cSlm <- function(y, x) {
    .Call(`_skewfit_cSlm`, y, x)
}

cEMMdl3 <- function(init_pa, init_ai, y, x, z, unimodal, max_steps, tol) {
    .Call(`_skewfit_cEMMdl3`, init_pa, init_ai, y, x, z, unimodal, max_steps, tol)
}

cEMMdl4 <- function(init_pa, init_ai, init_ci, y, x, z, unimodal, max_steps, tol) {
    .Call(`_skewfit_cEMMdl4`, init_pa, init_ai, init_ci, y, x, z, unimodal, max_steps, tol)
}

cPava0 <- function(y, w) {
    .Call(`_skewfit_cPava0`, y, w)
}

cPava <- function(y, w) {
    .Call(`_skewfit_cPava`, y, w)
}

cUfit <- function(y, x, unimodal) {
    .Call(`_skewfit_cUfit`, y, x, unimodal)
}

