# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cGetEw <- function(x, eta, sig2) {
    .Call(`_skewfit_cGetEw`, x, eta, sig2)
}

cSlm <- function(y, x) {
    .Call(`_skewfit_cSlm`, y, x)
}

cEMMdl3 <- function(init_pa, init_ai, y, x, z, unimodal, max_steps, tol) {
    .Call(`_skewfit_cEMMdl3`, init_pa, init_ai, y, x, z, unimodal, max_steps, tol)
}

cEMMdl4 <- function(pa, ai, ci, y, x, z, unimodal, max_steps, tol) {
    .Call(`_skewfit_cEMMdl4`, pa, ai, ci, y, x, z, unimodal, max_steps, tol)
}

cPava <- function(y, w) {
    .Call(`_skewfit_cPava`, y, w)
}

FPava <- function(y, w) {
    .Call(`_skewfit_FPava`, y, w)
}

FUfit <- function(y, w) {
    .Call(`_skewfit_FUfit`, y, w)
}

cIso <- function(y, unimodal) {
    .Call(`_skewfit_cIso`, y, unimodal)
}

